package kachuelitos.persistence.entity;

// Generated 07-sep-2014 23:17:15 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComentarioId generated by hbm2java
 */
@Embeddable
public class ComentarioId implements java.io.Serializable {

	private int idTrabajo;
	private int dniuser;
	private int idTrabajador;

	public ComentarioId() {
	}

	public ComentarioId(int idTrabajo, int dniuser, int idTrabajador) {
		this.idTrabajo = idTrabajo;
		this.dniuser = dniuser;
		this.idTrabajador = idTrabajador;
	}

	@Column(name = "idTrabajo", nullable = false)
	public int getIdTrabajo() {
		return this.idTrabajo;
	}

	public void setIdTrabajo(int idTrabajo) {
		this.idTrabajo = idTrabajo;
	}

	@Column(name = "DNIUser", nullable = false)
	public int getDniuser() {
		return this.dniuser;
	}

	public void setDniuser(int dniuser) {
		this.dniuser = dniuser;
	}

	@Column(name = "idTrabajador", nullable = false)
	public int getIdTrabajador() {
		return this.idTrabajador;
	}

	public void setIdTrabajador(int idTrabajador) {
		this.idTrabajador = idTrabajador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComentarioId))
			return false;
		ComentarioId castOther = (ComentarioId) other;

		return (this.getIdTrabajo() == castOther.getIdTrabajo())
				&& (this.getDniuser() == castOther.getDniuser())
				&& (this.getIdTrabajador() == castOther.getIdTrabajador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTrabajo();
		result = 37 * result + this.getDniuser();
		result = 37 * result + this.getIdTrabajador();
		return result;
	}

}
