package kachuelitos.persistence.entity;

// Generated 07-sep-2014 23:17:15 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tagcache generated by hbm2java
 */
@Entity
@Table(name = "tagcache", catalog = "mydb")
public class Tagcache implements java.io.Serializable {

	private int idTagCacheDni;
	private String contentTags;
	private Integer flagNewContent;

	public Tagcache() {
	}

	public Tagcache(int idTagCacheDni) {
		this.idTagCacheDni = idTagCacheDni;
	}

	public Tagcache(int idTagCacheDni, String contentTags,
			Integer flagNewContent) {
		this.idTagCacheDni = idTagCacheDni;
		this.contentTags = contentTags;
		this.flagNewContent = flagNewContent;
	}

	@Id
	@Column(name = "idTagCacheDni", unique = true, nullable = false)
	public int getIdTagCacheDni() {
		return this.idTagCacheDni;
	}

	public void setIdTagCacheDni(int idTagCacheDni) {
		this.idTagCacheDni = idTagCacheDni;
	}

	@Column(name = "contentTags", length = 500)
	public String getContentTags() {
		return this.contentTags;
	}

	public void setContentTags(String contentTags) {
		this.contentTags = contentTags;
	}

	@Column(name = "flagNewContent")
	public Integer getFlagNewContent() {
		return this.flagNewContent;
	}

	public void setFlagNewContent(Integer flagNewContent) {
		this.flagNewContent = flagNewContent;
	}

}
