package kachuelitos.persistence.entity;

// Generated 08-sep-2014 4:13:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trabajador generated by hbm2java
 */
@Entity
@Table(name = "trabajador", catalog = "mydb2")
public class Trabajador implements java.io.Serializable {

	private int trabajadorDniuser;
	private Float reputacionTrabajador;
	private String resumenTrabajador;
	private String experienciaTrabajador;

	public Trabajador() {
	}

	public Trabajador(int trabajadorDniuser) {
		this.trabajadorDniuser = trabajadorDniuser;
	}

	public Trabajador(int trabajadorDniuser, Float reputacionTrabajador,
			String resumenTrabajador, String experienciaTrabajador) {
		this.trabajadorDniuser = trabajadorDniuser;
		this.reputacionTrabajador = reputacionTrabajador;
		this.resumenTrabajador = resumenTrabajador;
		this.experienciaTrabajador = experienciaTrabajador;
	}

	@Id
	@Column(name = "Trabajador_DNIUser", unique = true, nullable = false)
	public int getTrabajadorDniuser() {
		return this.trabajadorDniuser;
	}

	public void setTrabajadorDniuser(int trabajadorDniuser) {
		this.trabajadorDniuser = trabajadorDniuser;
	}

	@Column(name = "ReputacionTrabajador", precision = 12, scale = 0)
	public Float getReputacionTrabajador() {
		return this.reputacionTrabajador;
	}

	public void setReputacionTrabajador(Float reputacionTrabajador) {
		this.reputacionTrabajador = reputacionTrabajador;
	}

	@Column(name = "ResumenTrabajador", length = 1000)
	public String getResumenTrabajador() {
		return this.resumenTrabajador;
	}

	public void setResumenTrabajador(String resumenTrabajador) {
		this.resumenTrabajador = resumenTrabajador;
	}

	@Column(name = "ExperienciaTrabajador", length = 1000)
	public String getExperienciaTrabajador() {
		return this.experienciaTrabajador;
	}

	public void setExperienciaTrabajador(String experienciaTrabajador) {
		this.experienciaTrabajador = experienciaTrabajador;
	}

}
