package kachuelitos.persistence.entity;

// Generated 07-sep-2014 22:39:05 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrabajoId generated by hbm2java
 */
@Embeddable
public class TrabajoId implements java.io.Serializable {

	private int idTrabajo;
	private int userDniuser;
	private int idServicio;
	private int idTrabajador;

	public TrabajoId() {
	}

	public TrabajoId(int idTrabajo, int userDniuser, int idServicio,
			int idTrabajador) {
		this.idTrabajo = idTrabajo;
		this.userDniuser = userDniuser;
		this.idServicio = idServicio;
		this.idTrabajador = idTrabajador;
	}

	@Column(name = "idTrabajo", nullable = false)
	public int getIdTrabajo() {
		return this.idTrabajo;
	}

	public void setIdTrabajo(int idTrabajo) {
		this.idTrabajo = idTrabajo;
	}

	@Column(name = "User_DNIUser", nullable = false)
	public int getUserDniuser() {
		return this.userDniuser;
	}

	public void setUserDniuser(int userDniuser) {
		this.userDniuser = userDniuser;
	}

	@Column(name = "idServicio", nullable = false)
	public int getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(int idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "idTrabajador", nullable = false)
	public int getIdTrabajador() {
		return this.idTrabajador;
	}

	public void setIdTrabajador(int idTrabajador) {
		this.idTrabajador = idTrabajador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrabajoId))
			return false;
		TrabajoId castOther = (TrabajoId) other;

		return (this.getIdTrabajo() == castOther.getIdTrabajo())
				&& (this.getUserDniuser() == castOther.getUserDniuser())
				&& (this.getIdServicio() == castOther.getIdServicio())
				&& (this.getIdTrabajador() == castOther.getIdTrabajador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTrabajo();
		result = 37 * result + this.getUserDniuser();
		result = 37 * result + this.getIdServicio();
		result = 37 * result + this.getIdTrabajador();
		return result;
	}

}
