package kachuelitos.persistence.entity;

// Generated 07-sep-2014 22:39:05 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name = "ubigeo", catalog = "mydb")
public class Ubigeo implements java.io.Serializable {

	private int idUbigeo;
	private String departamentoUbigeo;
	private String provinciaUbigeo;
	private String distritoUbigeo;

	public Ubigeo() {
	}

	public Ubigeo(int idUbigeo) {
		this.idUbigeo = idUbigeo;
	}

	public Ubigeo(int idUbigeo, String departamentoUbigeo,
			String provinciaUbigeo, String distritoUbigeo) {
		this.idUbigeo = idUbigeo;
		this.departamentoUbigeo = departamentoUbigeo;
		this.provinciaUbigeo = provinciaUbigeo;
		this.distritoUbigeo = distritoUbigeo;
	}

	@Id
	@Column(name = "idUbigeo", unique = true, nullable = false)
	public int getIdUbigeo() {
		return this.idUbigeo;
	}

	public void setIdUbigeo(int idUbigeo) {
		this.idUbigeo = idUbigeo;
	}

	@Column(name = "DepartamentoUbigeo", length = 45)
	public String getDepartamentoUbigeo() {
		return this.departamentoUbigeo;
	}

	public void setDepartamentoUbigeo(String departamentoUbigeo) {
		this.departamentoUbigeo = departamentoUbigeo;
	}

	@Column(name = "ProvinciaUbigeo", length = 45)
	public String getProvinciaUbigeo() {
		return this.provinciaUbigeo;
	}

	public void setProvinciaUbigeo(String provinciaUbigeo) {
		this.provinciaUbigeo = provinciaUbigeo;
	}

	@Column(name = "DistritoUbigeo", length = 45)
	public String getDistritoUbigeo() {
		return this.distritoUbigeo;
	}

	public void setDistritoUbigeo(String distritoUbigeo) {
		this.distritoUbigeo = distritoUbigeo;
	}

}
